const TARGETS = [...document.querySelectorAll('.target')];
const TOTALS = [...document.querySelectorAll('.total')]
const USERS = [...document.querySelectorAll('.user')];
const TYPES = [...document.querySelectorAll('.type')];
const BUTTONS = [...document.querySelectorAll('.button')];
const BODYS = [...document.querySelectorAll('.body')];
const BACKGROUNDS = [...document.querySelectorAll('.background')];
const OVERVIEWS = [...document.querySelectorAll('.overview')];
const TITLES = [...document.querySelectorAll('.title')];
const TEXTOPTIONMODES = [...document.querySelectorAll('.text-option-mode')];
const SUBTITLES = [...document.querySelectorAll('.subtitle')];
const MINTARGETS = [...document.querySelectorAll('.min-target')];
const DASBOARDTWOTOTALS = [...document.querySelectorAll('.dasboard-two-total')];
const DASBOARDTWOTYPES = [...document.querySelectorAll('.dasboard-two-type')];

button.addEventListener('click', () => {
   TARGETS.map((target) => target.classList.toggle('target-dark'))
   TOTALS.map((total) => total.classList.toggle('total-dark'));
   USERS.map((user) => user.classList.toggle('user-dark'));
   TYPES.map((type) => type.classList.toggle('type-dark'));
   BUTTONS.map((button) => button.classList.toggle('button-dark'));
   BODYS.map((body) => body.classList.toggle('body-dark'));
   BACKGROUNDS.map((background) => background.classList.toggle('background-dark'));
   OVERVIEWS.map((overview) => overview.classList.toggle('overview-dark'));
   TITLES.map((title) => title.classList.toggle('title-dark'));
   TEXTOPTIONMODES.map((textoptionmode) => textoptionmode.classList.toggle('textoptionmode-dark'));
   SUBTITLES.map((subtitle) => subtitle.classList.toggle('subtitle-dark'));
   MINTARGETS.map((mintarget) => mintarget.classList.toggle('min-target-dark'));
   DASBOARDTWOTOTALS.map((dasboardtwototal) => dasboardtwototal.classList.toggle('dasboard-two-total-dark'));
   DASBOARDTWOTYPES.map((dasboardtwotype) => dasboardtwotype.classList.toggle('dasboard-two-type-dark'));
});